# github: [Alexkkkkk]
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# custom: ["https://ton.org", "https://dedust.io"]
