"""Automatic error reporting to GitHub Issues."""

import logging
import os
import traceback
from datetime import datetime

import requests

from config import Config

log = logging.getLogger("error_reporter")


class GitHubReporter:
    def __init__(self, token: str = None, repo: str = None):
        self.token = token or os.getenv("GITHUB_TOKEN", "")
        self.repo = repo or os.getenv("GITHUB_REPO", "Alexkkkkk/GRINCH-GRAM")
        self.api_url = f"https://api.github.com/repos/{self.repo}/issues"
        self.enabled = bool(self.token and self.repo)
        if not self.enabled:
            log.warning("[GitHubReporter] Disabled")

    def create_issue(self, title: str, body: str, labels: list = None) -> dict:
        if not self.enabled:
            return {"ok": False, "error": "Disabled"}
        headers = {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github.v3+json",
        }
        payload = {
            "title": f"[BOT] {title}",
            "body": body,
            "labels": labels or ["bot-error", "auto-report"],
        }
        try:
            resp = requests.post(
                self.api_url, headers=headers, json=payload, timeout=15
            )
            if resp.status_code == 201:
                data = resp.json()
                log.info("Issue created: %s", data.get("html_url"))
                return {
                    "ok": True,
                    "issue_url": data.get("html_url"),
                    "issue_number": data.get("number"),
                }
            else:
                log.error("Failed: %s %s", resp.status_code, resp.text)
                return {"ok": False, "error": f"HTTP {resp.status_code}"}
        except Exception as e:
            log.error("Request failed: %s", e)
            return {"ok": False, "error": str(e)}

    def report_exception(self, exc: Exception, context: str = ""):
        tb = traceback.format_exc()
        title = f"{type(exc).__name__}: {str(exc)[:80]}"
        body = f"""**Time:** {datetime.utcnow().isoformat()} UTC\n**Context:** {context or 'N/A'}\n**Symbol:** {Config.GRID_SYMBOL}\n```python\n{tb}\n```\n---\n*Auto-generated by GRINCH-GRAM*"""
        return self.create_issue(title, body, ["bot-error", "auto-report", "bug"])

    def report_trade_error(
        self, side: str, level_id: int, price: float, error_msg: str
    ):
        title = f"Trade Failed: {side} @ {price} (Level {level_id})"
        body = f"**Time:** {datetime.utcnow().isoformat()} UTC\n**Side:** {side}\n**Level:** {level_id}\n**Price:** {price}\n**Error:** {error_msg}\n**Symbol:** {Config.GRID_SYMBOL}\n---\n*Auto-generated*"
        return self.create_issue(
            title, body, ["bot-error", "trade-failure", "auto-report"]
        )

    def report_grid_rebuild(self, old_center: float, new_center: float, reason: str):
        title = f"Grid Recentered: {old_center:.6f} -> {new_center:.6f}"
        body = f"**Time:** {datetime.utcnow().isoformat()} UTC\n**Reason:** {reason}\n**Old:** {old_center}\n**New:** {new_center}\n**Symbol:** {Config.GRID_SYMBOL}\n---\n*Auto-generated*"
        return self.create_issue(
            title, body, ["bot-info", "grid-rebuild", "auto-report"]
        )


_reporter = None


def get_reporter() -> GitHubReporter:
    global _reporter
    if _reporter is None:
        _reporter = GitHubReporter()
    return _reporter
